# Site settings
title: Project Management for Modern Teams | PM Cards
tag_text: Project Management Cards
description: A set of cards with quick-to-adopt tools and practices from the different schools of project management. For teams that want to co-create their way of working.
url: "https://pmcards.github.io"
baseurl: "https://pmcards.github.io"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]

gems:
  - jekyll-sitemap